### ISSUE TITLE
Get Narration to work for Menus

### ISSUE THREAD

**Issue by JRJurman** [RITAccess/accessible-scratch#7]
Get menus on the top bar to be narrated.

![image](https://cloud.githubusercontent.com/assets/326557/6088204/0cff504c-ae22-11e4-8f44-adb349ae61b0.png)

As a user, I want to hear the items I'm selecting in the menu, so that I understand what happens when I activate them.

**Comment by weswigham** [comment]
This _could_ be working in master now. The accessibility graph looks like it should - I have yet to try with a real screen reader, though. (Not that I'm experienced using one...)

**Comment by retrogamer80s** [comment]
Hi,

If on Mac you can use voiceover.  If on pc, you can download the trial version of jaws from freedom scientific.

Steph

**Comment by weswigham** [comment]
Seems to be functional according to accessibility debugger, so I'll mark this as done.
