### ISSUE TITLE
Get Narration to work for Panes

### ISSUE THREAD

**Issue by JRJurman** [RITAccess/accessible-scratch#8]
On hover, the narrator should be able to read the title of the pane, aka "Stage" for the image below
![image](https://cloud.githubusercontent.com/assets/326557/6088246/5de712b0-ae22-11e4-8d68-63253fe39c2e.png)

Panes are groups of elements which the user can interact with. Panes themselves do not describe elements that the user can interact with.

As a user, I want to be hear the name of the selected pane, so that I can better understand where my selection is.

**Comment by weswigham** [comment]
See comments on #37.
